---

- hosts: localhost
  vars:
    aws_cli_user: ec2-user
    aws_cli_group: ec2-user
    ansible_os_family: RedHat
    firewall_allowed_tcp_ports:
      - "22"
      - "8080" 
    java_packages: java-1.8.0-openjdk
    jenkins_version: 2.107.2
    jenkins_pkg_url: http://pkg.jenkins-ci.org/redhat-stable/ 
    jenkins_plugins: 
      - credentials
  roles:
    - { role: '../roles/wrapper/ansible-terraform' }
    - { role: '../roles/wrapper/aws_cli', become: yes, become_user: ec2-user }
    - { role: '../roles/third_party/geerlingguy.java', become: yes }
    - { role: '../roles/third_party/geerlingguy.jenkins', become: yes }